src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/command/template.java
src/main/java/frc/robot/subsystem/templateSubsystem.java
vendordeps/PathplannerLib.json

[#7] Added basic Constants and folders

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/Collect.java
src/main/java/frc/robot/subsystem/Collector.java

[#12] Created basic collector with beambreak

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/RunCollectorOnBeamBreak.java
src/main/java/frc/robot/subsystems/Collector.java

[#18] Cleaned up collector code and moved logic to new command

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/Swerve.java

[#4] get constants

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java

39 slow mode

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/AngleTowardTags.java
src/main/java/frc/robot/command/PointAtTag.java
src/main/java/frc/robot/subsystems/Swerve.java

added a command that rotates the robot toward an april tag using a PID loop

[#13] - point to tags

---

src/main/deploy/pathplanner/autos/limff.auto
src/main/deploy/pathplanner/paths/Limelight.path
src/main/java/frc/robot/subsystems/Swerve.java

46 limelight update

---

src/main/java/frc/robot/Constants.java

[#56] Got new offsets

---

src/main/java/frc/robot/subsystems/Pivot.java
src/main/java/frc/robot/subsystems/Shooter.java

Closes #32 
(done by carter and vilok)

[#32] - renamed angle function in pivot

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/Swerve.java

[#58] rhapsody constants

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/PointAtTag.java

Closes #44 
might wanna remove the button bindings later

[#44] - added lock on command and heading PID constant

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/Swerve.java

Closes #54 
Displays a boolean if in slow mode, also changes speed

[#54] display slow mode

---

src/main/deploy/pathplanner/paths/4-ST-[C1-C2-C3]-RF.path

Distance works very well based off of april tags by the limelight 3
Doesn't rotate new issue made
Closes #37

[#37] test initial autons

---

vendordeps/PathplannerLib.json

[#78] pathplanner dep

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/command/Collect.java
src/main/java/frc/robot/subsystems/Collector.java

[#72] cleaned collector, switched to top bottom

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/PointAtTag.java

[#49] move and angel

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/Collector.java
src/main/java/frc/robot/subsystems/Flywheel.java
src/main/java/frc/robot/subsystems/Indexer.java
src/main/java/frc/robot/subsystems/Pivot.java
src/main/java/frc/robot/subsystems/Swerve.java

[#89] Modified Can bus constants

---

src/main/java/frc/robot/Constants.java

[#92] New Constants

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/Main.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/Telemetry.java
src/main/java/frc/robot/command/Collect.java
src/main/java/frc/robot/command/PointAtTag.java
src/main/java/frc/robot/command/Shoot.java
src/main/java/frc/robot/subsystems/Collector.java
src/main/java/frc/robot/subsystems/Collision.java
src/main/java/frc/robot/subsystems/Flywheel.java
src/main/java/frc/robot/subsystems/Pivot.java
src/main/java/frc/robot/subsystems/Shooter.java
src/main/java/frc/robot/subsystems/Swerve.java

Merge this before the auton Changes
Closes #91

[#91] Formated and add comments

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/PointAtTag.java
src/main/java/frc/robot/command/tests/DriveTest.java
src/main/java/frc/robot/command/tests/DrivetrainSystemTest.java
src/main/java/frc/robot/command/tests/TurnSystemTest.java

[#118] change drive system test to robot relative

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/tests/DrivetrainSystemTest.java
src/main/java/frc/robot/command/tests/TurnSystemTest.java
src/main/java/frc/robot/command/tests/testCommands/DriveTest.java
src/main/java/frc/robot/command/tests/testCommands/TurnTest.java

[#120] cleaner system tests

---

.github/linter_suppressions.xml
.github/linter_suppressions_limited.xml
.github/sun_checks.xml
.github/workflows/gradle.yml
.github/workflows/linter.yml

[#121] enable linter to be run manually

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/command/Climb.java
src/main/java/frc/robot/command/ManualClimb.java
src/main/java/frc/robot/subsystems/Climber.java

Just visualization for climb rn, not gonna guarantee it'll work, but it shouldn't break anything.

[#127] mech visualization

---

src/main/deploy/pathplanner/autos/SM-3.auto
src/main/deploy/pathplanner/paths/1MeterSquareLL.path
src/main/deploy/pathplanner/paths/Linked points.path
src/main/deploy/pathplanner/paths/Run_Through_Pieces.path
src/main/deploy/pathplanner/paths/StraightOut.path

please pull this branch and see if the way points are on your computer
Closes #122

[#122] Added Linked-points

---

src/main/java/frc/robot/subsystems/Collector.java

[#137] detect if robot has piece

---

src/main/java/frc/robot/RobotContainer.java

deleted the disable and enable triggers in robot container
closes #146

[#146] deleted bad button bindings

---

src/main/java/frc/robot/command/Index.java

[#152] Made index command

---

src/main/java/frc/robot/RobotContainer.java

configured button bindings for driver and copilot for now 👀
Closes #150

[#150] configured button bindings for now

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/Pivot.java

[#158] add fused cancoder support

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/command/ChasePieces.java

Closes #138 
it works well but we need to test it with a collector (when we get it)

[#138] - tuned the heading controller

---

src/main/java/frc/robot/subsystems/LEDs.java

[#149] fixed blink

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/HapticFeedback.java

[#167] added haptic command

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/ChasePieces.java
src/main/java/frc/robot/command/PointAtTag.java
src/main/java/frc/robot/subsystems/Flywheel.java
src/main/java/frc/robot/subsystems/Limelights.java
src/main/java/frc/robot/subsystems/Swerve.java

[#189] implemented limelight subsystem

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/command/PointAtTag.java
src/main/java/frc/robot/subsystems/Flywheel.java

just removed some unused/deprecated code and renamed some variables.
Closes #193

[#193] - clean point at tags

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/Limelights.java

[#180] Limelight names

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/shoot/AmpShot.java
src/main/java/frc/robot/command/shoot/PodiumShot.java
src/main/java/frc/robot/command/shoot/PointBlankShot.java
src/main/java/frc/robot/command/shoot/SmartShoot.java
src/main/java/frc/robot/subsystems/Flywheel.java
src/main/java/frc/robot/subsystems/Pivot.java

Closes #165 
POV add set bias
Start + back resets to zero

[#165] Shooter biases

---

src/main/java/frc/robot/subsystems/Climber.java
src/main/java/frc/robot/subsystems/Swerve.java

[#202] Moved isTipped

---

src/main/java/frc/robot/command/PointAtTag.java
src/main/java/frc/robot/subsystems/Limelights.java
src/main/java/frc/robot/subsystems/Swerve.java

changed the names of limelight's pressure and champions to stopme and champs respectively. Names were changed due to a character limit for limelight names.
closes #204

[#204] changed the limelight names

---

src/main/java/frc/robot/RobotContainer.java
vendordeps/Phoenix6.json

Closes #225 
@Jeffthedoor They added TorqueCurrentFOC to simulator.

[#225][#123] Update Vendor dep

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/LEDs.java

[#229] added led collecting state

---

README.md

[#227] Update README.md

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/Climber.java
src/main/java/frc/robot/subsystems/Collector.java
src/main/java/frc/robot/subsystems/Flywheel.java
src/main/java/frc/robot/subsystems/Indexer.java

[#222] Switched to ThunderBird

---

src/main/java/frc/robot/Constants.java

Added a value for PivotConstants.ENCODER_TO_ROTOR_RATIO

[#223] - get pivot gear ratio

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/tests/ClimbSystemTest.java
src/main/java/frc/robot/command/tests/CollectorSystemTest.java
src/main/java/frc/robot/command/tests/DrivetrainSystemTest.java
src/main/java/frc/robot/command/tests/FlywheelSystemTest.java
src/main/java/frc/robot/command/tests/IndexerSystemTest.java
src/main/java/frc/robot/command/tests/PivotSystemTest.java
src/main/java/frc/robot/command/tests/SingSystemTest.java
src/main/java/frc/robot/command/tests/TurnSystemTest.java
src/main/java/frc/robot/command/tests/testcmds/ClimbTest.java
src/main/java/frc/robot/command/tests/testcmds/CollectorTest.java
src/main/java/frc/robot/command/tests/testcmds/DriveTest.java
src/main/java/frc/robot/command/tests/testcmds/FlywheelTest.java
src/main/java/frc/robot/command/tests/testcmds/IndexerTest.java
src/main/java/frc/robot/command/tests/testcmds/PivotTest.java
src/main/java/frc/robot/command/tests/testcmds/TurnTest.java

[#240] Cleanup systests

---

src/main/java/frc/robot/Constants.java

[#245] fixed slowmode

---

src/main/java/frc/robot/Constants.java

changed the CAN ids for the robot map constants
closes #247

[#247] changed the CAN constants

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/Swerve.java

[#248] swapy swap

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/Flywheel.java
src/main/java/frc/robot/subsystems/Pivot.java

also corrected one seemingly erroneous variable name, and added basic logging to pivot and flywheel.
gl with the robot today guys, sucks I cant be there.
let this PR be my PID legacy... even though I might just end up retuning it when I get back :)
closes #255

[#255] added FalconTuners to pivot and Flywheel

---

src/main/java/frc/robot/RobotContainer.java

closes #258 added a filter to joysticks with .1 deadband

[#258] added a controller filter

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/MoveToPose.java
src/main/java/frc/robot/command/PointAtTag.java
src/main/java/frc/robot/command/tests/DrivetrainSystemTest.java
src/main/java/frc/robot/command/tests/TurnSystemTest.java
src/main/java/frc/robot/command/tests/testcmds/DriveTest.java
src/main/java/frc/robot/command/tests/testcmds/TurnTest.java
src/main/java/frc/robot/subsystems/LEDs.java
src/main/java/frc/robot/subsystems/Swerve.java

[#252] move slow mode to swerve

---

src/main/java/frc/robot/command/ChasePieces.java

[#254] - cleaned up chase pieces and adjusted for new code

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/Swerve.java

269 update drivetrain request function

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/PointAtTag.java
src/main/java/frc/robot/command/tests/testcmds/DriveTest.java
src/main/java/frc/robot/command/tests/testcmds/TurnTest.java
src/main/java/frc/robot/subsystems/Swerve.java

Deadband and ramping is done directly on the driver controller, may use for coPilot later
Commands available are the ones in use, can add more if needed but nothing currently would need one
Closes #271

[#271] Cleaned up and fixed all drive commands

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/command/ChasePieces.java
src/main/java/frc/robot/command/Climb.java
src/main/java/frc/robot/command/Collect.java
src/main/java/frc/robot/command/MoveToPose.java
src/main/java/frc/robot/command/PointAtTag.java
src/main/java/frc/robot/command/SmartCollect.java
src/main/java/frc/robot/command/shoot/AmpShot.java
src/main/java/frc/robot/command/shoot/CandC1.java
src/main/java/frc/robot/command/shoot/CandC2.java
src/main/java/frc/robot/command/shoot/CandC3.java
src/main/java/frc/robot/command/shoot/CandLine.java
src/main/java/frc/robot/command/shoot/PodiumShot.java
src/main/java/frc/robot/command/shoot/PointBlankShot.java
src/main/java/frc/robot/command/shoot/SmartShoot.java
src/main/java/frc/robot/command/shoot/Stow.java
src/main/java/frc/robot/subsystems/Climber.java
src/main/java/frc/robot/subsystems/Collector.java
src/main/java/frc/robot/subsystems/Flywheel.java
src/main/java/frc/robot/subsystems/Indexer.java
src/main/java/frc/robot/subsystems/LEDs.java
src/main/java/frc/robot/subsystems/Pivot.java
src/main/java/frc/robot/subsystems/Swerve.java

[#259] - made every logger (that can) use suppliers

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/Collector.java
src/main/java/frc/robot/subsystems/Flywheel.java
src/main/java/frc/robot/subsystems/Indexer.java
src/main/java/frc/robot/subsystems/Pivot.java

[#166] New offsets and inverts

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/Pivot.java
src/main/java/frc/robot/subsystems/Swerve.java

[#286] Offset and Angles

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/LEDs.java

[#291] added second led string

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/LEDs.java

[#293] fix leds

---

src/main/java/frc/robot/subsystems/Flywheel.java
src/main/java/frc/robot/subsystems/Pivot.java

[#289] Added limit switch functions

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java

Leaving the nervo subsystem, but removed all calls
Closes #296

[#296] Fixed main + Removed Nervo

---

src/main/deploy/pathplanner/autos/1-BF-Mobility.auto
src/main/deploy/pathplanner/autos/1-TF-Mobility.auto
src/main/deploy/pathplanner/paths/SB-BL.path
src/main/deploy/pathplanner/paths/ST-TL.path
src/main/deploy/pathplanner/paths/TF-ST.path

Added 2 autons and the paths to help support them

[#161] Make mobility autons

---

src/main/java/frc/robot/RobotContainer.java

Temp once xbox controller filter is fixed reimplement that
Closes #302

[#302] Fix driver input

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/LEDs.java

[#306] updated LEDS

---

src/main/java/frc/robot/subsystems/LEDs.java

[#308] update leds

---

src/main/java/frc/robot/command/shoot/Stow.java

Bit silly but used in auton
Please merge this before Flywheel
Closes #274

[#274] Stow command

---

build.gradle

[#315] New version will test on robot

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/SmartCollect.java
src/main/java/frc/robot/subsystems/Swerve.java

Needs to test reverse indexing after hitting exit beambreak. May need to disable for Kettering if comms is a problem. Pivot angle check needs to be tested (may need to req pivot subsystem).
Closes #305

[#305] Smart Collect logic

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/shoot/SmartShoot.java
src/main/java/frc/robot/subsystems/Flywheel.java
src/main/java/frc/robot/subsystems/LEDs.java
src/main/java/frc/robot/subsystems/Pivot.java
src/main/java/frc/robot/subsystems/Swerve.java

Base code, tune with new issue
Closes #318

[#318] implemented interpolation map

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/shoot/PointBlankShot.java
src/main/java/frc/robot/command/shoot/SmartShoot.java

[#164] Working point blank, and tuning

---

src/main/java/frc/robot/RobotContainer.java

[#48] temp disable logger

---

src/main/java/frc/robot/command/shoot/PointBlankShot.java

Closes #325 
uncommented original code, removed shuffleboard stuff

[#325] - reverted point blank

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/LEDs.java
src/main/java/frc/robot/subsystems/Swerve.java

[#310] led blink on startup

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/shoot/PointBlankShot.java
src/main/java/frc/robot/subsystems/Flywheel.java
src/main/java/frc/robot/subsystems/Swerve.java

[#321] complete interpolation map

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/Pivot.java

Closes #336 
no longer jerky when at certain angles, smoother

[#336] - fixed pivot PID

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/Flywheel.java

[#335] Tuned KV no Kp

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/LEDs.java

[#343] updated leds

---

src/main/java/frc/robot/subsystems/Climber.java
src/main/java/frc/robot/subsystems/Collector.java
src/main/java/frc/robot/subsystems/Flywheel.java
src/main/java/frc/robot/subsystems/Indexer.java

[#319] Apply configs

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/Collector.java

[#341] collector use velocity voltage

---

src/main/java/frc/robot/subsystems/Indexer.java

346 add a timeout to collector beambreak

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/PointAtPoint.java
src/main/java/frc/robot/command/PointAtTag.java
src/main/java/frc/robot/subsystems/Collector.java

[#351] remove deadbands

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/ChasePieces.java
src/main/java/frc/robot/subsystems/Collector.java
src/main/java/frc/robot/subsystems/Pivot.java

[#277] - test full chase pieces

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/shoot/AutonCand/AmpShotAuton.java
src/main/java/frc/robot/command/shoot/AutonCand/CandC1.java
src/main/java/frc/robot/command/shoot/AutonCand/CandC2.java
src/main/java/frc/robot/command/shoot/AutonCand/CandC3.java
src/main/java/frc/robot/command/shoot/AutonCand/CandLine.java
src/main/java/frc/robot/command/shoot/AutonCand/PointBlankShotAuton.java
src/main/java/frc/robot/command/shoot/PointBlankShot.java
src/main/java/frc/robot/command/shoot/SourceCollect.java

[#329] test and fix point blank

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/shoot/SourceCollect.java
src/main/java/frc/robot/command/shoot/Tune.java
src/main/java/frc/robot/subsystems/Flywheel.java

[#360] interpolation tune

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/SmartCollect.java
src/main/java/frc/robot/subsystems/Flywheel.java

[#366] added flywheel stop

---

src/main/java/frc/robot/Constants.java

[#364] Tune

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/CollectAndGo.java

created the new collect and go command for auton
closes #371

[#371] created the collect and go command

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/LEDs.java

[#367] update leds

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/command/shoot/Tune.java
src/main/java/frc/robot/subsystems/Flywheel.java

[#376] Tube shooter

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/LEDs.java

[#382] updated beambreak testing leds

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/ChasePieces.java
src/main/java/frc/robot/command/SmartCollect.java
src/main/java/frc/robot/command/tests/CycleSytemTest.java

[#383] Add reverse flywheel collect logic

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/PointAtPoint.java

Fixes point at point when always blue

Point at point always blue

---

src/main/java/frc/robot/command/shoot/AmpShot.java
src/main/java/frc/robot/command/shoot/AutonCand/AmpShotAuton.java
src/main/java/frc/robot/command/shoot/Tune.java
src/main/java/frc/robot/command/tests/testcmds/FlywheelTest.java
src/main/java/frc/robot/subsystems/Flywheel.java

fixed the names for flywheel methods
closes #401

[#401] changed the names (literally just used f2 lol)

---

src/main/java/frc/robot/subsystems/Swerve.java

[#400] fixed distanceToTarget()

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/command/PointAtPoint.java

[#406] added a few things to help point at point in auton (needs testing)

---

src/main/java/frc/robot/RobotContainer.java

[#404] no buzz in auton!

---

src/main/java/frc/robot/subsystems/Indexer.java

[#408] added debouncers for entry and exit beambreaks in indexer

---

src/main/java/frc/robot/subsystems/Swerve.java

Added ramp rate configuration for Swerve drivetrain motors

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/Pivot.java

Things:
- Initial Tuned Pivot (will need to be adjusted for aluminum rollers)
- swapped to new gear ratio
- added an arm feed forward because the lower reduction needs it
- swapped back to phoenix built in pid to make use of the super friendly arm feed forward :)

[#392] rhapsody pivot

---

src/main/java/frc/robot/subsystems/Swerve.java

[#414] - commented out ramp rate

---

src/main/java/frc/robot/subsystems/Swerve.java

fixed a spelling mistake with swerve shuffleboard
closes #419

[#419] fixed the spelling mistake :)

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/Flywheel.java
src/main/java/frc/robot/subsystems/Pivot.java

[#412] rhapsody flywheel

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/SmartCollect.java
src/main/java/frc/robot/command/shoot/AmpShot.java
src/main/java/frc/robot/command/shoot/AutonCand/AmpShotAuton.java
src/main/java/frc/robot/command/shoot/AutonCand/CandC1.java
src/main/java/frc/robot/command/shoot/AutonCand/CandC2.java
src/main/java/frc/robot/command/shoot/AutonCand/CandC3.java
src/main/java/frc/robot/command/shoot/AutonCand/CandLine.java
src/main/java/frc/robot/command/shoot/AutonCand/PointBlankShotAuton.java
src/main/java/frc/robot/command/shoot/PodiumShot.java
src/main/java/frc/robot/command/shoot/PointBlankShot.java
src/main/java/frc/robot/command/shoot/SmartShoot.java
src/main/java/frc/robot/command/shoot/SourceCollect.java
src/main/java/frc/robot/command/shoot/Stow.java
src/main/java/frc/robot/command/shoot/Tune.java
src/main/java/frc/robot/command/tests/PivotAngleTest.java
src/main/java/frc/robot/subsystems/Pivot.java
src/main/java/frc/robot/subsystems/PivotMercury.java
src/main/java/frc/robot/subsystems/PivotRhapsody.java

[#424] Mercury vs Rhapsody pivot

---

src/main/deploy/pathplanner/autos/Test Chase Auton.auto
src/main/deploy/pathplanner/paths/New New Path.path
src/main/deploy/pathplanner/paths/New Path.path
src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/command/ChasePieces.java

[#425] - auton chase

---

src/main/java/frc/robot/subsystems/Limelights.java

[#432] made champs be monitored for pose updating

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/Collector.java
src/main/java/frc/robot/subsystems/Indexer.java
src/main/java/frc/robot/subsystems/PivotRhapsody.java

[#435] updated maps and beambreak calls

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/Swerve.java

[#438] made brake work with y button

---

src/main/java/frc/robot/subsystems/Climber.java
src/main/java/frc/robot/subsystems/Collector.java
src/main/java/frc/robot/subsystems/Flywheel.java
src/main/java/frc/robot/subsystems/Indexer.java
src/main/java/frc/robot/subsystems/PivotMercury.java
src/main/java/frc/robot/subsystems/PivotRhapsody.java
src/main/java/frc/robot/subsystems/Swerve.java

[#441] added shuffleboard values for subsystems

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/Indexer.java

[#449] did one line so flywheel inverses when indexer goes down

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/PathToPose.java

[#461] - cleaned up path to pose

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java

[#464] Moved logging

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/Robot.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/Telemetry.java
src/main/java/frc/robot/command/ChasePieces.java
src/main/java/frc/robot/command/CollectAndGo.java
src/main/java/frc/robot/command/PointAtPoint.java
src/main/java/frc/robot/command/PointAtTag.java
src/main/java/frc/robot/command/Sing.java
src/main/java/frc/robot/command/shoot/AutonCand/AmpShotAuton.java
src/main/java/frc/robot/command/shoot/AutonCand/CandC1.java
src/main/java/frc/robot/command/shoot/AutonCand/CandC2.java
src/main/java/frc/robot/command/shoot/AutonCand/CandC3.java
src/main/java/frc/robot/command/shoot/AutonCand/CandLine.java
src/main/java/frc/robot/command/shoot/AutonCand/PointBlankShotAuton.java
src/main/java/frc/robot/subsystems/LEDs.java
src/main/java/frc/robot/subsystems/Pivot.java
src/main/java/frc/robot/subsystems/PivotMercury.java
src/main/java/frc/robot/subsystems/PivotRhapsody.java

[#467] Cleanup

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/PointAtPoint.java

[#473] - faster point at point

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/Climber.java

changed the encoder offset for rhapsody's pivot
closes #476

[#476] Encoder Offset

---

src/main/java/frc/robot/subsystems/Indexer.java

[#483] changed indexerMotor variable to motor

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/shoot/SmartShoot.java

[#485] retune shot maps

---

src/main/java/frc/robot/Constants.java

[#488] Tuned Amp limit

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/AutonPointAtTag.java
src/main/java/frc/robot/command/PointAtTag.java
src/main/java/frc/robot/command/SetStopMePipeline.java

[#491] Auton point at tag named commands

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java

[#506] button box mappings

---

src/main/java/frc/robot/RobotContainer.java

[#507] - swapped joysticks for climber controls

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/AutonSmartCollect.java

[#526] fix auto smart collect

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/command/CollisionDetection.java
src/main/java/frc/robot/command/shoot/SmartShoot.java
src/main/java/frc/robot/command/shoot/preAim.java
src/main/java/frc/robot/subsystems/Collector.java
src/main/java/frc/robot/subsystems/Flywheel.java
src/main/java/frc/robot/subsystems/Indexer.java

change isMercury() to a variable to avoid checking if the robot is mercury every time the function is called

[#530] change isMercury to var

---

.github/dependabot.yml

[#537] Dependabot Milestone
